### ISSUE TITLE
Empty fdf matrix in MakeAPAMatrix.MakeMatrix()

### ISSUE THREAD

**Issue by zmx21** [venkatajonnakuti/PolyAMiner-Bulk#5]
Hello, 

I have received the following error while running the provided test script 
`Traceback (most recent call last):
  File "/remote/idiap.svm/group.genomics/zmxu/PolyAMiner-Bulk/Demo/../PolyA-miner.py", line 486, in <module>
    main()
  File "/remote/idiap.svm/group.genomics/zmxu/PolyAMiner-Bulk/Demo/../PolyA-miner.py", line 283, in main
    if MakeAPAMatrix.MakeMatrix(args.o, args.p, args.outPrefix, args.pa_p, args.pa_a, args.pa_m, controls, treated, args.apa_min, args.gene_min, args.mode,controls+treated,logBook,args.pa_usage) == 1:
  File "/remote/idiap.svm/group.genomics/zmxu/PolyAMiner-Bulk/lib/MakeAPAMatrix.py", line 172, in MakeMatrix
    cdf = fdf[['feature_id', 'gene_id'] + controls]
  File "/idiap/home/zmxu/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/idiap/home/zmxu/.local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 6114, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/idiap/home/zmxu/.local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 6175, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['feature_id', 'gene_id', 'control1_.subset.sorted',\n       'control2_.subset.sorted', 'control3_.subset.sorted'],\n      dtype='object')] are in the [columns]"`

Upon further investigation, it looks like the fdf dataframe was never populated and remains empty - hence the error. Any idea what could be happening? Thanks!

**Comment by Zejian-Wang** [comment]
Hi zmx21,

I got the same error about it, have you solve this issues?

Thank you!

Best,
ZJ
